/**
 * SemanticEditorPanel.test.tsx — Strategy-UX-1B / VOL-E2E-1 / RSI-1D.
 *
 * Verifies that the rule builder uses human-friendly labels while preserving
 * internal instance IDs in serialized condition data.
 *
 * Coverage:
 *  1.  Panel renders without crashing
 *  2.  "No strategy semantics" empty state shown when semantics=null
 *  3.  Create Semantics button initialises empty editor
 *  4.  tool_output operand renders a <select> (not a free-text input)
 *  5.  toolOutputOptions labels appear in the dropdown
 *  6.  Selecting a friendly label stores the internal value (instance_id.output)
 *  7.  Existing condition with internal ref shows correct option selected
 *  8.  Backward compat: unknown ref (old saved strategy) preserved as fallback option
 *  9.  Multiple distinct tool options shown correctly
 * 10.  Serialization: saved semantics use internal instance_id refs, not labels
 * 11.  Volume tool option has label "Volume.volume" in dropdown
 * 12.  Volume MA option has label "Volume.volume_ma" in dropdown
 * 13.  No duplicate "Volume.volume" entries when both volume tools present
 * 14.  Selecting volume.volume left operand stores correct ref on save
 * 15.  RSI-1D: rsi_midline option present in dropdown when toolset includes rsi_midline
 * 16.  RSI-1D: rsi_smoothing option present in dropdown when toolset includes rsi_smoothing
 * 17.  RSI-1D: no duplicate RSI entries when rsi, rsi_midline, rsi_smoothing all present
 * 18.  RSI-1D: selecting rsi_midline.rsi_midline stores correct internal ref on save
 * 19.  RSI-1D: selecting rsi_smoothing.rsi_smoothing stores correct internal ref on save
 * 20.  RSI-1D: rsi option still present alongside rsi_midline / rsi_smoothing (no collision)
 * 21.  RSI-1D: rsi_midline ref displayed correctly in existing condition (no label bleed)
 */
import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { SemanticEditorPanel } from '../SemanticEditorPanel'
import type { StrategySemantics } from '../../types/semantics'
import type { ToolOutputOption } from '../SemanticEditorPanel'

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const EMA9_OPTION:  ToolOutputOption = { label: 'EMA (9).value',   value: 'ema_9_close.value' }
const EMA21_OPTION: ToolOutputOption = { label: 'EMA (21).value',  value: 'ema_21_close.value' }
const RSI14_OPTION: ToolOutputOption = { label: 'RSI (14).rsi',    value: 'rsi_14.rsi' }

const MOCK_OPTIONS: ToolOutputOption[] = [EMA9_OPTION, EMA21_OPTION, RSI14_OPTION]

// Volume tool options — generated by generateCompactLabel when both volume tools are in toolset.
// Neither "volume" nor "volume_ma" appears in IDENTITY_FIELDS, so the prefix is just the tool
// shortName "Volume". Output name is appended after ".".
const VOL_OPTION:    ToolOutputOption = { label: 'Volume.volume',    value: 'volume.volume' }
const VOL_MA_OPTION: ToolOutputOption = { label: 'Volume.volume_ma', value: 'volume_ma.volume_ma' }

const VOLUME_OPTIONS: ToolOutputOption[] = [VOL_OPTION, VOL_MA_OPTION]
const ALL_OPTIONS:    ToolOutputOption[] = [...MOCK_OPTIONS, VOL_OPTION, VOL_MA_OPTION]

// RSI family options — rsi uses IDENTITY_FIELDS (period → "RSI (14)"),
// rsi_midline and rsi_smoothing have no IDENTITY_FIELDS entry so their labels
// are the bare short names with output appended.
const RSI_MIDLINE_OPTION:   ToolOutputOption = { label: 'RSI Midline.rsi_midline', value: 'rsi_midline.rsi_midline' }
const RSI_SMOOTHING_OPTION: ToolOutputOption = { label: 'RSI Smoothing.rsi_smoothing', value: 'rsi_smoothing.rsi_smoothing' }
const RSI_ALL_OPTIONS: ToolOutputOption[] = [RSI14_OPTION, RSI_MIDLINE_OPTION, RSI_SMOOTHING_OPTION]

function makeSemantics(leftRef = '', rightRef = '0'): StrategySemantics {
  return {
    entry_rules: [{
      condition_group: {
        operator: 'AND',
        conditions: [{
          left:     { kind: 'tool_output', ref: leftRef },
          operator: '>',
          right:    { kind: 'constant', ref: rightRef },
          label:    null,
        }],
        label: null,
      },
      label: null,
      notes: null,
    }],
    exit_rules: [],
    metadata: { version: '1.0' },
  }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('SemanticEditorPanel — Strategy-UX-1B', () => {
  const mockSave     = vi.fn()
  const mockValidate = vi.fn()

  beforeEach(() => {
    vi.clearAllMocks()
    mockSave.mockResolvedValue(null)
    mockValidate.mockResolvedValue({ valid: true, errors: [] })
  })

  it('1. renders without crashing', () => {
    expect(() =>
      render(<SemanticEditorPanel semantics={null} onSave={mockSave} onValidate={mockValidate} />)
    ).not.toThrow()
  })

  it('2. shows empty state when semantics=null', () => {
    render(<SemanticEditorPanel semantics={null} onSave={mockSave} onValidate={mockValidate} />)
    expect(screen.getByText(/No strategy semantics/i)).toBeInTheDocument()
  })

  it('3. Create Semantics button initialises editor', async () => {
    render(<SemanticEditorPanel semantics={null} onSave={mockSave} onValidate={mockValidate} />)
    fireEvent.click(screen.getByText('+ Create Semantics'))
    await waitFor(() => expect(screen.getByText('Entry Rules')).toBeInTheDocument())
  })

  it('4. tool_output operand renders a <select> (not free-text input)', () => {
    render(
      <SemanticEditorPanel
        semantics={makeSemantics('ema_9_close.value')}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={MOCK_OPTIONS}
      />
    )
    // Should be a <select> not a datalist-linked input
    const selects = screen.getAllByTestId('tool-output-select')
    expect(selects.length).toBeGreaterThanOrEqual(1)
  })

  it('5. toolOutputOptions labels appear as dropdown options', () => {
    render(
      <SemanticEditorPanel
        semantics={makeSemantics()}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={MOCK_OPTIONS}
      />
    )
    const select = screen.getAllByTestId('tool-output-select')[0]
    const optionTexts = Array.from(select.querySelectorAll('option')).map(o => o.textContent)
    expect(optionTexts).toContain('EMA (9).value')
    expect(optionTexts).toContain('EMA (21).value')
    expect(optionTexts).toContain('RSI (14).rsi')
  })

  it('6. selecting friendly label stores internal value', () => {
    let capturedLeft = ''
    const savedSemantics: StrategySemantics[] = []
    mockSave.mockImplementation(async (s: StrategySemantics) => {
      savedSemantics.push(s)
      capturedLeft = s.entry_rules[0].condition_group.conditions[0].left.ref
      return s
    })

    render(
      <SemanticEditorPanel
        semantics={makeSemantics()}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={MOCK_OPTIONS}
      />
    )

    const leftSelect = screen.getAllByTestId('tool-output-select')[0]
    fireEvent.change(leftSelect, { target: { value: 'ema_9_close.value' } })
    fireEvent.click(screen.getByText('Save'))

    return waitFor(() => {
      expect(capturedLeft).toBe('ema_9_close.value')  // internal ID stored, not label
    })
  })

  it('7. existing condition with internal ref shows the correct option selected', () => {
    render(
      <SemanticEditorPanel
        semantics={makeSemantics('ema_21_close.value')}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={MOCK_OPTIONS}
      />
    )
    const leftSelect = screen.getAllByTestId('tool-output-select')[0] as HTMLSelectElement
    // The select value should be the internal ID
    expect(leftSelect.value).toBe('ema_21_close.value')
  })

  it('8. backward compat: unknown ref is preserved as fallback option', () => {
    const oldRef = 'sma_fast.value'  // ID from a strategy saved before UX-1A
    render(
      <SemanticEditorPanel
        semantics={makeSemantics(oldRef)}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={MOCK_OPTIONS}  // does not contain sma_fast
      />
    )
    const leftSelect = screen.getAllByTestId('tool-output-select')[0] as HTMLSelectElement
    // Value should still show the old raw ref (fallback option added automatically)
    expect(leftSelect.value).toBe('sma_fast.value')
    const optionValues = Array.from(leftSelect.querySelectorAll('option')).map(o => o.value)
    expect(optionValues).toContain('sma_fast.value')
  })

  it('9. multiple distinct tool options all present', () => {
    render(
      <SemanticEditorPanel
        semantics={makeSemantics()}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={MOCK_OPTIONS}
      />
    )
    const selects = screen.getAllByTestId('tool-output-select')
    const firstSelect = selects[0]
    const optionCount = firstSelect.querySelectorAll('option').length
    // blank + 3 real options
    expect(optionCount).toBeGreaterThanOrEqual(3)
  })

  it('10. serialization: saved conditions use instance_id, not display labels', async () => {
    const saved: StrategySemantics[] = []
    mockSave.mockImplementation(async (s: StrategySemantics) => { saved.push(s); return s })

    render(
      <SemanticEditorPanel
        semantics={makeSemantics('ema_9_close.value')}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={MOCK_OPTIONS}
      />
    )

    fireEvent.click(screen.getByText('Save'))

    await waitFor(() => expect(saved.length).toBeGreaterThan(0))

    const ref = saved[0].entry_rules[0].condition_group.conditions[0].left.ref
    // Must be the internal ID, never the human-friendly label
    expect(ref).toBe('ema_9_close.value')
    expect(ref).not.toContain('EMA')
  })

  // -------------------------------------------------------------------------
  // VOL-E2E-1 — Volume tool dropdown option contract
  // -------------------------------------------------------------------------

  it('11. Volume tool option has label "Volume.volume" in dropdown', () => {
    render(
      <SemanticEditorPanel
        semantics={makeSemantics()}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={VOLUME_OPTIONS}
      />
    )
    const select = screen.getAllByTestId('tool-output-select')[0]
    const optionTexts = Array.from(select.querySelectorAll('option')).map(o => o.textContent)
    expect(optionTexts).toContain('Volume.volume')
  })

  it('12. Volume MA option has label "Volume.volume_ma" in dropdown', () => {
    render(
      <SemanticEditorPanel
        semantics={makeSemantics()}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={VOLUME_OPTIONS}
      />
    )
    const select = screen.getAllByTestId('tool-output-select')[0]
    const optionTexts = Array.from(select.querySelectorAll('option')).map(o => o.textContent)
    expect(optionTexts).toContain('Volume.volume_ma')
  })

  it('13. no duplicate "Volume.volume" entries when both volume tools present', () => {
    render(
      <SemanticEditorPanel
        semantics={makeSemantics()}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={ALL_OPTIONS}
      />
    )
    const select = screen.getAllByTestId('tool-output-select')[0]
    const optionTexts = Array.from(select.querySelectorAll('option')).map(o => o.textContent)
    const volEntries = optionTexts.filter(t => t === 'Volume.volume')
    expect(volEntries).toHaveLength(1)
  })

  it('14. selecting volume.volume left operand stores correct ref on save', async () => {
    const saved: StrategySemantics[] = []
    mockSave.mockImplementation(async (s: StrategySemantics) => { saved.push(s); return s })

    render(
      <SemanticEditorPanel
        semantics={makeSemantics('volume.volume')}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={ALL_OPTIONS}
      />
    )

    fireEvent.click(screen.getByText('Save'))

    await waitFor(() => expect(saved.length).toBeGreaterThan(0))

    const ref = saved[0].entry_rules[0].condition_group.conditions[0].left.ref
    expect(ref).toBe('volume.volume')
    expect(ref).not.toContain('Volume.')  // must be the internal ID, not the label
  })

  // ---------------------------------------------------------------------------
  // RSI-1D: RSI family (rsi, rsi_midline, rsi_smoothing) dropdown tests
  // ---------------------------------------------------------------------------

  it('15. rsi_midline option present in dropdown when toolset includes rsi_midline', () => {
    render(
      <SemanticEditorPanel
        semantics={makeSemantics()}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={RSI_ALL_OPTIONS}
      />
    )
    const select = screen.getAllByTestId('tool-output-select')[0]
    const optionTexts = Array.from(select.querySelectorAll('option')).map(o => o.textContent)
    expect(optionTexts).toContain('RSI Midline.rsi_midline')
  })

  it('16. rsi_smoothing option present in dropdown when toolset includes rsi_smoothing', () => {
    render(
      <SemanticEditorPanel
        semantics={makeSemantics()}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={RSI_ALL_OPTIONS}
      />
    )
    const select = screen.getAllByTestId('tool-output-select')[0]
    const optionTexts = Array.from(select.querySelectorAll('option')).map(o => o.textContent)
    expect(optionTexts).toContain('RSI Smoothing.rsi_smoothing')
  })

  it('17. no duplicate RSI entries when rsi, rsi_midline, rsi_smoothing all present', () => {
    render(
      <SemanticEditorPanel
        semantics={makeSemantics()}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={RSI_ALL_OPTIONS}
      />
    )
    const select = screen.getAllByTestId('tool-output-select')[0]
    const optionTexts = Array.from(select.querySelectorAll('option')).map(o => o.textContent)
    const rsiEntries = optionTexts.filter(t => t === 'RSI (14).rsi')
    expect(rsiEntries).toHaveLength(1)
  })

  it('18. selecting rsi_midline.rsi_midline stores correct internal ref on save', async () => {
    const saved: StrategySemantics[] = []
    mockSave.mockImplementation(async (s: StrategySemantics) => { saved.push(s); return s })

    render(
      <SemanticEditorPanel
        semantics={makeSemantics('rsi_midline.rsi_midline')}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={RSI_ALL_OPTIONS}
      />
    )

    fireEvent.click(screen.getByText('Save'))
    await waitFor(() => expect(saved.length).toBeGreaterThan(0))

    const ref = saved[0].entry_rules[0].condition_group.conditions[0].left.ref
    expect(ref).toBe('rsi_midline.rsi_midline')
    expect(ref).not.toContain('RSI Midline.')
  })

  it('19. selecting rsi_smoothing.rsi_smoothing stores correct internal ref on save', async () => {
    const saved: StrategySemantics[] = []
    mockSave.mockImplementation(async (s: StrategySemantics) => { saved.push(s); return s })

    render(
      <SemanticEditorPanel
        semantics={makeSemantics('rsi_smoothing.rsi_smoothing')}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={RSI_ALL_OPTIONS}
      />
    )

    fireEvent.click(screen.getByText('Save'))
    await waitFor(() => expect(saved.length).toBeGreaterThan(0))

    const ref = saved[0].entry_rules[0].condition_group.conditions[0].left.ref
    expect(ref).toBe('rsi_smoothing.rsi_smoothing')
    expect(ref).not.toContain('RSI Smoothing.')
  })

  it('20. rsi option still present alongside rsi_midline / rsi_smoothing (no collision)', () => {
    render(
      <SemanticEditorPanel
        semantics={makeSemantics()}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={RSI_ALL_OPTIONS}
      />
    )
    const select = screen.getAllByTestId('tool-output-select')[0]
    const optionTexts = Array.from(select.querySelectorAll('option')).map(o => o.textContent)
    expect(optionTexts).toContain('RSI (14).rsi')
    expect(optionTexts).toContain('RSI Midline.rsi_midline')
    expect(optionTexts).toContain('RSI Smoothing.rsi_smoothing')
  })

  it('21. rsi_midline ref displayed correctly in existing condition (no label bleed)', () => {
    render(
      <SemanticEditorPanel
        semantics={makeSemantics('rsi_midline.rsi_midline')}
        onSave={mockSave}
        onValidate={mockValidate}
        toolOutputOptions={RSI_ALL_OPTIONS}
      />
    )
    const select = screen.getAllByTestId('tool-output-select')[0] as HTMLSelectElement
    // The select should have the internal value selected, not a label string
    expect(select.value).toBe('rsi_midline.rsi_midline')
  })
})
